Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -1,40 +1,50 @@
-name: Run Delete Query
+name: PostgreSQL Connection Check
 
 on:
   push:
     branches:
-      - main  # adjust this to your main branch name
+      - main
 
 jobs:
-  delete_query:
+  check_postgresql_connection:
     runs-on: ubuntu-latest
     services:
       postgres:
         image: postgres:latest
+        env:
+          POSTGRES_DB: credentials
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: Jtrip23@
         ports:
           - 5432:5432
-        env:
-          DATABASE_HOST: 127.0.0.1
-          DATABASE_PORT: 5432  
-          DATABASE_NAME: credentials  
-          DATABASE_USER: postgres
-          DATABASE_PASSWORD: Jtrip23@
-    
+        options: --network github_network
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.8  # choose the appropriate Python version
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.x'
 
-    - name: Install dependencies
-      run: pip install psycopg2-binary pip install --upgrade pip # install psycopg2
+      - name: Install dependencies
+        run: |
+          pip install psycopg2-binary
 
-    - name: Run Python script
-      run: python script.py
+      - name: Retry connecting to PostgreSQL
+        id: connect
+        run: |
+          for i in {1..5}; do
+            python script.py && break || sleep 5;
+          done
 
+      - name: Check connection status
+        run: |
+          if [ ${{ steps.connect.exitcode }} -eq 0 ]; then
+            echo "Connection successful."
+          else
+            echo "Error: Connection failed after multiple attempts."
+            exit 1
+          fi
 
-   
